### ISSUE TITLE
Reproduce experiments.

### ISSUE THREAD

**Issue by rodrigogutierrezm** [georgeliu233/Scene-Rep-Transformer#1]
I am trying to reproduce your experiments but I am facing some difficulties. 

- I am not able to build the scenarios.
- I have run the code using the scenario provided by smarts (previously built) and I get the following error: "FileNotFoundError: [Errno 2] No such file or directory: './test_results/rb_left_turn_new_test.json'"
It looks like some files are missing in the repository.
- When I fix this by creating the missing files I get a new error.

Maybe I am doing something wrong or maybe the repository is not complete yet.

Please let me know if you can help me to run your experiments.

Thank you.

**Comment by georgeliu233** [comment]
Hi, Sorry for the late response! 

The failure of building experimental scenarios and running the rule-based baseline might be caused by the deprecated SMARTS grammar, of which I previously built on ver 0.4.x

This is also a preliminary release for this work (based on old version of certain packages), and I plan to make an entire update  (scenario based on current SMARTS version, easier pipeline for reproductions, etc.) soon after the camera-ready for this paper.
Stay tuned :)
